CREATE TABLE CLIENTES
(
	ID_CLIENTE SERIAL PRIMARY KEY,
	NOMBRE VARCHAR(60) NOT NULL,
	APELLIDO VARCHAR(60) NOT NULL,
	DIRECCION VARCHAR(255) NOT NULL,
	TELEFONO VARCHAR(10) NULL,
	DOC_IDENTIF VARCHAR(80) NOT NULL
);


CREATE TABLE CUENTAS
(
	CUENTA VARCHAR(40) PRIMARY KEY,
	ID_CLIENTE INTEGER REFERENCES CLIENTES(ID_CLIENTE),
	SALDO NUMERIC NOT NULL
);


CREATE TABLE TRANSACCIONES
(
	ID_TRANSACCION SERIAL PRIMARY KEY,
	CUENTA_ORIGEN VARCHAR(40) REFERENCES CUENTAS(CUENTA),
	CUENTA_DESTINO VARCHAR(40) REFERENCES CUENTAS(CUENTA),
	IMPORTE INTEGER NOT NULL,
	FECHA_MOVIMIENTO DATE NOT NULL
);
