
--OBTENER EL REGISTRO DE TODAS LAS TRANASACCIONES REALIZADAS
SELECT *
FROM TRANSACCIONES;


--ELIMINACION POR ERROR DE LOS REGISTROS DE TODAS LAS TRANSACCIONES PARA DETERMINADA CUENTA
DELETE 
FROM TRANSACCIONES
WHERE CUENTA_ORIGEN = '2530 10 2000 1234567890'