Diseño del sistema Distribuido

 El sistema consta de tres nodos los cuales pueden funcionar autónomamente sin embargo también pueden compartir y obtener información de los demás sistemas, a continuación se muestra el diagrama de la topología:

ACÁ FIGURA DE TOPOLOGÍA…

 Sin embargo el sistema puede ser escalable horizontalmente, su core está construido de tal forma que puedan agregarse más nodos, estos deben ser configurados y agregados a la tabla REGION para darles de alta o baja.

Algoritmo del Proceso de Replicación Online



AGREGAR REGIONES

OBTENER TODOS LOS NODOS ACTIVOS
	POR CADA NODO ACTIVO
		INSERTAR REGION
	FIN
FIN

INSERTAR REGION EN NODO LOCAL

SI EXISTE ALGÚN ERROR
	REGISTRAR ERROR EN LOG


ELIMINAR ASIGNACIONES DE EQUIPO

OBTENER TODOS LOS NODOS ACTIVOS
	POR CADA NODO ACTIVO
		OBTENER DATOS EXCURSION REMOTO
		OBTENER DATOS EQUIPO REMOTO
		OBTENER DATOS TURISTA REMOTO
			ELIMINAR REGISTRO
	FIN
FIN

ELIMINAR ASIGNACION DE EQUIPO EN NODO LOCAL

SI EXISTE ALGÚN ERROR 
	REGISTRAR ERROR EN LOG
	

ELIMINAR ASIGNACIONES DE EXCURSIONES

OBTENER TODOS LOS NODOS ACTIVOS
	POR CADA NODO ACTIVO
		OBTENER DATOS EXCURSION REMOTO
		OBTENER DATOS TURISTA REMOTO
			ELIMINAR REGISTRO
	FIN
FIN

ELIMINAR ASIGNACION DE EXCURSION EN NODO LOCAL

SI EXISTE ALGÚN ERROR 
	REGISTRAR ERROR EN LOG


ELIMINAR EQUIPO

OBTENER TODOS LOS NODOS ACTIVOS
	POR CADA NODO ACTIVO
		OBTENER DATOS EQUIPO REMOTO
•	ELIMINAR REGISTROS EN ASIGNACIÓN DE EQUIPOS QUE DEPENDAN DEL EQUIPO A ELIMINAR
•	ELIMINAR EQUIPO
	FIN
FIN
•	ELIMINAR REGISTROS EN ASIGNACIÓN DE EQUIPOS QUE DEPENDAN DEL EQUIPO A ELIMINAR EN NODO LOCAL
•	ELIMINAR EQUIPO EN NODO LOCAL

SI EXISTE ALGÚN ERROR 
	REGISTRAR ERROR EN LOG


ELIMINAR EXCURSIÓN

OBTENER TODOS LOS NODOS ACTIVOS
	POR CADA NODO ACTIVO
		OBTENER DATOS EXCURSION REMOTO
•	ELIMINAR REGISTROS EN ASIGNACIÓN DE EXCURSIONES QUE DEPENDAN DE LA EXCURSION A ELIMINAR
•	ELIMINAR REGISTROS EN ASIGNACIÓN DE EQUIPOS QUE DEPENDAN DE LA EXCURSION A ELIMINAR
•	ELIMINAR EXCURSION
	FIN
FIN
•	ELIMINAR REGISTROS EN ASIGNACIÓN DE EXCURSIONES QUE DEPENDAN DE LA EXCURSION A ELIMINAR EN NODO LOCAL
•	ELIMINAR REGISTROS EN ASIGNACIÓN DE EQUIPOS QUE DEPENDAN DE LA EXCURSION A ELIMINAR EN NODO LOCAL
•	ELIMINAR EXCURSION EN NODO LOCAL

SI EXISTE ALGÚN ERROR 
	REGISTRAR ERROR EN LOG


ELIMINAR TURISTA

OBTENER TODOS LOS NODOS ACTIVOS
	POR CADA NODO ACTIVO
		OBTENER DATOS EXCURSION REMOTO
•	ELIMINAR REGISTROS EN ASIGNACIÓN DE EXCURSIONES QUE DEPENDAN DEL TURISTA A ELIMINAR
•	ELIMINAR REGISTROS EN ASIGNACIÓN DE EQUIPOS QUE DEPENDAN DEL TURISTA A ELIMINAR
•	ELIMINAR TURISTA
	FIN
FIN
•	ELIMINAR REGISTROS EN ASIGNACIÓN DE EXCURSIONES QUE DEPENDAN DEL TURISTA A ELIMINAR
•	ELIMINAR REGISTROS EN ASIGNACIÓN DE EQUIPOS QUE DEPENDAN DEL TURISTA A ELIMINAR
•	ELIMINAR TURISTA

SI EXISTE ALGÚN ERROR 
	REGISTRAR ERROR EN LOG


ELIMINAR RUTA

OBTENER TODOS LOS NODOS ACTIVOS
	POR CADA NODO ACTIVO
		OBTENER DATOS EXCURSION REMOTO
		OBTENER DATOS SITIO TURISTICO REMOTO
			ELIMINAR RUTA
	FIN
FIN

ELIMINAR RUTA EN NODO LOCAL

SI EXISTE ALGÚN ERROR 
	REGISTRAR ERROR EN LOG


ELIMINAR SITIO TURISTICO

OBTENER TODOS LOS NODOS ACTIVOS
	POR CADA NODO ACTIVO
		OBTENER DATOS SITIO TURISTICO REMOTO
•	ELIMINAR REGISTROS EN RUTA QUE DEPENDAN DEL SITIO TURISTICO A ELIMINAR
•	ELIMINAR SITIO TURISTICO
	FIN
FIN

ELIMINAR SITIO TURISTICO EN NODO LOCAL

SI EXISTE ALGÚN ERROR 
	REGISTRAR ERROR EN LOG




MODIFICAR DEPARTAMENTO

OBTENER TODOS LOS NODOS ACTIVOS
	POR CADA NODO ACTIVO
		ACTUALIZAR DEPARTAMENTO
	FIN
FIN

ACTUALIZAR DEPARTAMENTO EN NODO LOCAL

SI EXISTE ALGÚN ERROR 
	REGISTRAR ERROR EN LOG



MODIFICAR MUNICIPIO

OBTENER TODOS LOS NODOS ACTIVOS
	POR CADA NODO ACTIVO
		ACTUALIZAR MUNICIPIO
	FIN
FIN

ACTUALIZAR MUNICIPIO EN NODO LOCAL

SI EXISTE ALGÚN ERROR 
	REGISTRAR ERROR EN LOG




MODIFICAR PAIS

OBTENER TODOS LOS NODOS ACTIVOS
	POR CADA NODO ACTIVO
		ACTUALIZAR PAIS
	FIN
FIN

ACTUALIZAR PAIS EN NODO LOCAL

SI EXISTE ALGÚN ERROR 
	REGISTRAR ERROR EN LOG







MODIFICAR EQUIPO

OBTENER TODOS LOS NODOS ACTIVOS
	POR CADA NODO ACTIVO
		OBTENER DATOS EQUIPO REMOTO
                ACTUALIZAR EQUIPO
	FIN
FIN

ACTUALIZAR EQUIPO EN NODO LOCAL

SI EXISTE ALGÚN ERROR 
	REGISTRAR ERROR EN LOG




MODIFICAR EXCURSION

OBTENER TODOS LOS NODOS ACTIVOS
	POR CADA NODO ACTIVO
		OBTENER DATOS EXCURSION REMOTO
                ACTUALIZAR EXCURSION
	FIN
FIN

ACTUALIZAR EXCURSION EN NODO LOCAL

SI EXISTE ALGÚN ERROR 
	REGISTRAR ERROR EN LOG



MODIFICAR REGION

OBTENER TODOS LOS NODOS ACTIVOS
	POR CADA NODO ACTIVO
                ACTUALIZAR REGION
	FIN
FIN

ACTUALIZAR REGION EN NODO LOCAL

SI EXISTE ALGÚN ERROR 
	REGISTRAR ERROR EN LOG




MODIFICAR SITIO TURISTICO

OBTENER TODOS LOS NODOS ACTIVOS
	POR CADA NODO ACTIVO
		OBTENER DATOS SITIO TURISTICO REMOTO
                ACTUALIZAR SITIO TURISTICO
	FIN
FIN

ACTUALIZAR SITIO TURISTICO EN NODO LOCAL

SI EXISTE ALGÚN ERROR 
	REGISTRAR ERROR EN LOG





MODIFICAR TIPO DOCUMENTO

OBTENER TODOS LOS NODOS ACTIVOS
	POR CADA NODO ACTIVO
		OBTENER DATOS TIPO DOCUMENTO REMOTO
                ACTUALIZAR TIPO DOCUMENTO
	FIN
FIN

ACTUALIZAR TIPO DOCUMENTO EN NODO LOCAL

SI EXISTE ALGÚN ERROR 
	REGISTRAR ERROR EN LOG




MODIFICAR TURISTA

OBTENER TODOS LOS NODOS ACTIVOS
	POR CADA NODO ACTIVO
		OBTENER DATOS TURISTA REMOTO
                ACTUALIZAR TURISTA
	FIN
FIN

ACTUALIZAR TURISTA EN NODO LOCAL

SI EXISTE ALGÚN ERROR 
	REGISTRAR ERROR EN LOG







